### ISSUE TITLE
使用中遇到任何BUG，请在这里留言反馈，我会及时的跟进和回复你

### ISSUE THREAD

**Issue by pdown2020** [pdown2020/pdown#1]
### 使用中遇到任何BUG，请在这里留言反馈，我会及时的跟进和回复你

**使用中遇到任何BUG，请在这里留言反馈，我会及时的跟进和回复你**

> 留言时务必详尽的描述你下载的链接，遇到的问题，具体的操作等。我才能跟进检查。如果只留言说：程序崩溃了，我也是会崩溃的

**Comment by pdown2020** [comment]
> 留言时务必详尽的描述你下载的链接，遇到的问题，具体的操作，附上截图等。我才能跟进检查。如果只留言说：程序崩溃了，我也是会崩溃的

**Comment by bbmimi** [comment]
![TIM截图20200321092407](https://user-images.githubusercontent.com/47265748/77216512-c2a1d780-6b55-11ea-90aa-135b26a7508d.png)
下载没速度.

**Comment by pdown2020** [comment]
嗯，，，，，，今天用户太多，我百度VIP账号卡住了，我在调整拉取策略，所以今天下载会很卡，无限拉取（因为实际上可能没有真的在拉取，我在改后台，，，，）


新项目，小众这里人太多了（主要是很多人下载的链接体积都很大），多包涵，我在改，等1–2天再试试吧


今天我在改拉取策略，明天的任务是上阿里的CDN。这样2天后速度就快点了





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "bbmimi"<notifications@github.com&gt;; 
发送时间: 2020年3月21日(星期六) 上午9:25
收件人: "pdown2020/pdown"<pdown@noreply.github.com&gt;; 
抄送: "own2020"<own2020@foxmail.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [pdown2020/pdown] 使用中遇到任何BUG，请在这里留言反馈，我会及时的跟进和回复你 (#1)





 

 下载没速度.

**Comment by bbmimi** [comment]
了解了解,,感谢!

**Comment by 15258947493** [comment]
我想问一下，蓝奏云链接的提取码是什么？

**Comment by laozhong** [comment]
啥也别说，支持，请把二维码放到首页

**Comment by 15258947493** [comment]
什么意思？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Aningood"<notifications@github.com&gt;; 
发送时间: 2020年3月23日(星期一) 中午1:54
收件人: "pdown2020/pdown"<pdown@noreply.github.com&gt;; 
抄送: "180726071@qq.com"<180726071@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [pdown2020/pdown] 使用中遇到任何BUG，请在这里留言反馈，我会及时的跟进和回复你 (#1)





 
啥也别说，支持，请把二维码放到首页

**Comment by LJLHLH** [comment]
希望作者之后能加一下高分屏优化啦。高分屏界面实在是太小了,看不清。

**Comment by pdown2020** [comment]
关于高分屏优化

其实用到的界面库SOUI是支持DPI的，同样c++调一下winapi也很方便，唯一的问题就是，适配根本不理想。最理想的方案是做2份界面（包括2套图标、渲染用到的图片等等）。因为软件并没有定型（稳定版本），只要有任意一点改动，就需要改两个界面。太乱了。我就还没来得及做

我本身已经考虑到高分屏，你会注意到软件的文字，间隔都比较大。你没看到我的屏幕，在27寸液晶屏 1920*1080 分辨率（非高分屏）是这样的
----嗯我竟然不会插图，，，，，去项目首页里看1920.png这个图片----
巨大。为的就是在高分屏，文字可以显得大一点。另外吧，在我笔记本上15.6寸1920x1080全高清屏。我看的是一点也不小啊。（系统设置文字125%）

你最好截个图给我看

**Comment by stm8866** [comment]
![QQ图片20200326193223](https://user-images.githubusercontent.com/62581687/77642398-8d074f00-6f98-11ea-92a7-862a0325d2f8.png)
创建文件夹失败怎么回事

**Comment by stm8866** [comment]
刚刚试了下  下到桌面可以 速度100多k
