### ISSUE TITLE
似乎有个小bug…

### ISSUE THREAD

**Issue by Itzamana** [pdown2020/pdown#10]
下载文件到根目录的话，会出错，显示“创建文件夹失败”，如图

![无标题.png](https://i.loli.net/2020/03/27/cnYt8jfszh4GiwQ.png)

**Comment by pdown2020** [comment]
嗯，是的，还有极少数链接，文件名含有特定特殊字符时，也会创建失败。将会在下个版本中一起修复

现在先请不要直接保存在根目录。随便建个文件夹就可以了


感谢您的反馈

**Comment by pdown2020** [comment]
蓝奏云 3-27 14:15 下载地址 https://www.lanzous.com/iap0e0j

此问题已被修正
