### ISSUE TITLE
有打算开源吗

### ISSUE THREAD

**Issue by chinuno-usami** [pdown2020/pdown#12]
开源之后大家可以一起维护更新

**Comment by pdown2020** [comment]
客户端是c++，用到了SOUI3，SQLite，Curl，GoogleBase，等等，界面都是我自己设计后用PS贴图
具体的代码因为是个人项目，又乱又杂，还有一堆BUG。实在羞于出手。等以后项目稳定了会考虑开源客户端的部分代码，因为SOUI就是开源的
