### ISSUE TITLE
是哪里出问题了吗?今天一直拉取中...

### ISSUE THREAD

**Issue by czghzc** [pdown2020/pdown#14]
是哪里出问题了吗?今天一直拉取中...

![image](https://user-images.githubusercontent.com/23645596/77812382-e75cf880-70db-11ea-8a44-88b61c4f735d.png)

**Comment by pdown2020** [comment]
嗯，我服务器IP被百度屏蔽了，刚看到，已经更换IP。有很长的队列，有的等了。抱歉

**Comment by pdown2020** [comment]
主要还是新上线，没有足够的缓存数据，以后数据多了，就不需要频繁的从百度拉取了，那就快了

**Comment by czghzc** [comment]
辛苦你了,为大家服务
