### ISSUE TITLE
提一个小小的建议

### ISSUE THREAD

**Issue by czghzc** [pdown2020/pdown#15]
![image](https://user-images.githubusercontent.com/23645596/77998144-2fda1780-7363-11ea-804d-e97d03f2554a.png)
有时候只是需要一个网盘文件夹里的其中的某一个文件,可是因为整个文件夹会有很多个文件,而导致体积超过要求而不能下载.
现在提一个小小的建议,能不能根据所选择的文件来限定,如果所有选择的文件在要求的体积以内,也可以正常下载.

**Comment by pdown2020** [comment]
嗯 ，您的建议我看到了，感谢反馈，这样我才能发现不足。  

你说的是很合理的，也是很有必要的。  
但是我现在按照整个链接计算，其实并不是我没想到，而是为了限制。我解释一下啊：：：  

第一个是现在下载逻辑的问题  
1 我们下载是按照整个链接去下载的（有的链接里面有几百个文件，如果是所有的链接都按照文件一个一个的去下载，会导致QPS太高被百度屏蔽IP）  
2 假如有一个链接内有1个1kb（xx链接），1个4GB（某电影），一共 2个文件，你点击下载1kb，我们实际上是需要下载1kb+4GB的。  
  
第二个是现在限额调整的问题  
1 现在的限额因为人多被我调整为100MB，其实以后还会调回去的。  
2 假设是根据选择文件的体积限制，会造成我们数据库中非常混乱，一部分链接是完整下载的，一部分链接是部分下载的（超过100MB）  
3 加入今天限制调整为300MB，就会导致一个问题，以前的，部分下载的，_但体积》100MB，《300MB的_这部分文件。怎么处理？他现在合适了，那就应该拉取过来，但实际上很多链接早就失效了。  这个不细说了，总之是一团乱麻。  


所以我其实想说的就是，道理很对，但实际操作起来问题太多，所以我就直接按照链接去处理了。并不是按照你的建议去实行的。

**Comment by pdown2020** [comment]
另外，其实我还考虑到文件管理的问题，一般就是，能用PDown就用，不能用就保存到我的网盘，用百度网盘下载（或者其他工具下载）。很少有人喜欢：我用PDown勾选下载一部分文件，然后再用百度网盘勾选下载另外一部分文件，最后我在把这些文件合并到一个文件夹里。
  
多乱啊，你得注意哪些已经下载了，哪些没有下载。。。  

最后如果你确实需要这个功能，可以通过先保存到我的网盘（你自己的网盘），然后在网盘勾选部分文件（单个100MB以内的），创建分享链接，把这个链接提交PDown下载。这样就实现了部分PDown，部分百度网盘的最终目的  
  
我知道操作都是很繁琐的，哪个也不方便。我以后会尽可能的提高限制的

**Comment by czghzc** [comment]
其实你那边数据库里可以按照单个文件来记录,用户下载时如果下载一个链接里面的一个文件,那么你就刚好也只下载一个文件,如果是多个文件,那么为了避免QPS太高的问题,就可以整个链接下载下来,然后只把用户需要的文件发给用户
这样的话,可能和你现在的程序逻辑冲突比较大,改动成本比较高
我只是想当然的说(俗话说,站着说话不腰疼的那种,哈哈^-^),你可以忽略

**Comment by pdown2020** [comment]
嗯嗯，回复的晚了。放心我不是玻璃心，你可以畅所欲言，互相交流吗。

其实单个文件下载和整个链接下载和链接内部分文件下载，这3个操作是需要调用百度的不同api的（是指具体的参数，方式不一样）。

仅从技术上去讨论啊，整个链接下载，只需要提供链接ID，就可以了。链接内部分文件下载，需要先遍历解析出链接内的所有文件，然后post想要下载的文件id才行。
这个遍历解析的操作吧，又可能会涉及到QPS了。因为每个链接内文件数量都不一样。这样一来技术上需要改动的比较多，程序一复杂，BUG就容易多，需要很长时间的调试才能稳定。这个对用户体验太不好了。
大部分人并没有这个需求，却可能因为我调整这个导致他不能用。

你也能看到项目刚上线的前10天，实在是太不稳定了，基本上我都是半天闭服，半天开服这样。昨天和今天是唯一稳定的2日天。所以我不敢折腾了。。。。

我还是那个思想，我认为大部分人都是这样考虑：一个链接内的文件，那就是完整的，要不都下，要不都不下。缺哪个文件也不行。部分文件用PDown，部分文件用百度网盘，因为一个文件来回切的操作根本不合理。我直接都用百度网盘（或者其他工具）不好吗？

因为这个思路，我才根本不考虑去折腾了


另外备注一下QPS，我根本还没测试出来百度的QPS策略，他并不是一分钟xx请求就屏蔽了这么简单，他的触发很突兀，感觉没啥规律。你比如有一次，晚上1点多，10分钟才有一个链接需要下载，他就给我ban了。大白天的时候很频繁了，他倒是没事。
