### ISSUE TITLE
感谢您的作品，真是帮了大忙了

### ISSUE THREAD

**Issue by IchijoHLL** [pdown2020/pdown#16]
我没啥技术水平，也不知道目前拉取的排序是什么规则，就想提一个很主观的建议，建议按照拉取文件的大小进行排序而不是开始拉取文件的时间先后

**Comment by pdown2020** [comment]
en ,多谢反馈

关于排序的问题，因为我已经限制100MB,500MB了，所以排序的方式已经无关紧要了

我想你提这个建议是遇到了长时间拉取的BUG，所以说明一下


现在，正常情况下，用户提交的链接，都可以在提交后1-3分钟内拉取完成开始下载，我们也调整了非登录用户的下载限速，现在下载很快的

但是，你看，有但是，

1 有的时候有的文件会莫名其妙的没速度，这个不是我的问题，是百度网盘本身没速度，同时在下载，其他的文件都有速度，就这个文件一点速度都没有或者反复失败

我猜测是因为这个文件比较冷门，所以百度把他放到低频存储区域了，遇到需要下载时，百度需要先“解冻”，所以要等很久才有速度。

2 有的时候会因为网络问题，后台程序BUG，服务器系统更新重启，等等等等，总之是很多奇奇怪怪的问题，导致后台程序卡住了，这个一般就是要等待拉取好几个小时（等到我打开后台看到程序卡住了手动重启）


我在研究提示方式，以后会越来越正常的。

**Comment by IchijoHLL** [comment]
您费心，我没怎么遇见过奇奇怪怪的问题，因为下载的东西不是很大其次使用的次数也不是很多。祝您学业有成，答辩顺利！
