### ISSUE TITLE
软件确实能解决一些应急需求，但有一点问题需要作者回复一下

### ISSUE THREAD

**Issue by Kakile** [pdown2020/pdown#17]
PDown在Windows 10 1909版本运行下，Windows Defend会报病毒

警报级别：严重
类别：特洛伊木马
详细信息：这个程序很危险，而且执行来自攻击者的命令。

**Comment by pdown2020** [comment]
嗯，自v1.0.19.142开始，win10自带的杀软就开始报毒了，

我也不知道为什么，我也不知道怎么修改才能不报毒。

我以后会把下个版本软件体积弄大一点，据说这样不容易报毒

**Comment by xlc520** [comment]
为什么用户那里一直没有开放呢 @pdown2020

**Comment by pdown2020** [comment]
可以看一下我发的  关于杀毒软件误报.md

**Comment by pdown2020** [comment]
> 为什么用户那里一直没有开放呢 @pdown2020

人太多，短信费很贵的，现在已经调整成登录和非登录限速一样了。登录只是可以搜索（国家要求实名制）。另外因为项目上线时间不长，加上搜索算法不强，搜索很鸡肋的，搜不到什么有用的东西的，所以就没开放。等以后数据多了，我调整下搜索算法再开放

**Comment by xlc520** [comment]
> > 为什么用户那里一直没有开放呢 @pdown2020
> 
> 人太多，短信费很贵的，现在已经调整成登录和非登录限速一样了。登录只是可以搜索（国家要求实名制）。另外因为项目上线时间不长，加上搜索算法不强，搜索很鸡肋的，搜不到什么有用的东西的，所以就没开放。等以后数据多了，我调整下搜索算法再开放

好的。
