### ISSUE TITLE
无限拉取问题

### ISSUE THREAD

**Issue by iceloX** [pdown2020/pdown#2]
非常感谢！开发此类产品，已经Star，根据我目前的使用情况来看，还是不能正常下载，存在无限拉取问题！

**Comment by pdown2020** [comment]
感谢反馈

这两天--尤其是20日晚-21日整天。确实存在无限拉取问题。原因是程序BUG+用户下载的大文件太多。

1 有的BUG，真的只有特定情境才能触发，所以我确实测试时不够到位，遇到BUG改BUG就得涉及到服务器（为了尽量少改动客户端）
我一动服务器，就得暂停--恢复，真实地狱。。我太难了

2 用户增长的比我预料的多+快。尤其是大文件的下载需求，现在的问题是卡在拉取（从百度网盘下载文件）。情况有很多（比如文件被删除啊，VIP也没速度啊，拉取的策略啊种种）我在处理。预计2-3天后，会显著的提升拉取的速度和下载的速度。

总之，给我几天时间，会好的。无限拉取会解决的

**Comment by pdown2020** [comment]
另外：对于无限拉取的链接，你等半天再试，基本就成功了。我会手动对部分出错的链接，重新拉取。等我调整好，就不需要这么麻烦了
