### ISSUE TITLE
什么时候开启注册呢

### ISSUE THREAD

**Issue by duke135** [pdown2020/pdown#21]
什么时候开启注册呢

**Comment by pdown2020** [comment]
人太多，短信费很贵的，现在已经调整成登录和非登录限速一样了。登录只是可以搜索（国家要求实名制）。另外因为项目上线时间不长，加上搜索算法不强，搜索很鸡肋的，搜不到什么有用的东西的，所以就没开放。等以后数据多了，我调整下搜索算法再开放
