### ISSUE TITLE
希望可以留一个联系方式，有很重要的事情告知！

### ISSUE THREAD

**Issue by 17683863152** [pdown2020/pdown#22]
如题

**Comment by pdown2020** [comment]
您应该在这里直接留言具体的 事情

**Comment by 17683863152** [comment]
我有一个公众号 主要是推荐一些好玩的电脑软件和手机软件，想让您在软件上加入我的公众号名片。



---原始邮件---
发件人: "pdown2020"<notifications@github.com&gt;
发送时间: 2020年4月9日(周四) 晚上8:28
收件人: "pdown2020/pdown"<pdown@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"Paload"<1391542927@qq.com&gt;;
主题: Re: [pdown2020/pdown] 希望可以留一个联系方式，有很重要的事情告知！ (#22)




 
您应该在这里直接留言具体的 事情

**Comment by pdown2020** [comment]
呃，这个我不懂啊，这是个纯粹的免费的个人软件，现在并没有接受捐赠/广告的打算啊。

**Comment by 17683863152** [comment]
emmm，我也是大学生，很喜欢用你的软件，我想了下，我公众号面向对象和你软件的用户很吻合~


------------------&nbsp;Original&nbsp;------------------

**Comment by pdown2020** [comment]
实际上我也没打算让很多人都知道（因为我财力有限，人多了我根本负担不起）。我只在小众软件上发过一次自荐，之后就没有再宣传过了。不知道大家都是怎么找到的。。。。呵呵

**Comment by 17683863152** [comment]
酒香不怕巷子深，我觉得我们可以聊一下公众号的盈利方式

www.all0.cn在线影院欢迎您


&nbsp;




------------------&nbsp;Original&nbsp;------------------

**Comment by pdown2020** [comment]
这么说不知道合适不合适，但请别误会，我发布出来主要还是学习目的，上线20多天，也确实让我学到了很多（比如用户量的并发控制，技术上的各种BUG，软件流程上的各种优化，项目的各个阶段的实施）。现在我只想稳定的，做一个咸鱼。PDown以后会怎么发展我根本没想过的，所以并没有准备好这方面的事。感谢你的留言，但请允许我拒绝，因为只要涉及到钱的问题，就比较复杂了，我懒得去操作，有限的精力主要还是放在学习上去。抱歉

**Comment by 17683863152** [comment]
好的，没问题
&nbsp;

www.all0.cn在线影院欢迎您


&nbsp;




------------------&nbsp;Original&nbsp;------------------

**Comment by dream0880113** [comment]
我是台灣的使用者，請問為什麼會一直出現這個訊息呢?
![1586594913136](https://user-images.githubusercontent.com/63494628/79039514-51b18500-7c14-11ea-8dfb-8f3ca746a4f5.jpg)
