### ISSUE TITLE
pandownload刚挂~

### ISSUE THREAD

**Issue by yassinzhou** [pdown2020/pdown#25]

**Comment by Leeking-wang** [comment]
不盈利，只挂在GitHub，应该没问题。可惜了pandownload真的很好用，搜索和下载学习资料。

**Comment by yangzuxin** [comment]
你有源代码吗

**Comment by pdown2020** [comment]
感谢大家的提醒，请参阅 [关于PD被办和百度权益问题.md](https://github.com/pdown2020/pdown/blob/master/关于PD被办和百度权益问题.md)

**Comment by czghzc** [comment]
只能这么说,BD真无耻
