### ISSUE TITLE
这个功能是不是可以做成p2p的

### ISSUE THREAD

**Issue by yz23095913** [pdown2020/pdown#27]
比如会员登陆这个APP,注册一下,然后非会员APP的能过服务器找到这个会员APP.
然后就可以p2p干和pdown一样的事情了.

**Comment by pdown2020** [comment]
你的这个思路很有趣，我来分析一下

我理解的你的意思是：

小王有百度的VIP会员，他登录PDown。然后小李没有VIP，但可以通过PDown连接到小王，利用小王的账号实现高速下载，这样可以减轻PDown的压力，不用排队等待

应该没理解错吧？

#### 问题1.小王有百度VIP会员，为啥要登录到PDown，让别人用他的VIP会员？学雷锋吗？
  
PDown事实上确实是学雷锋哦，当然从我主观上讲还是属于我花学费练技术
  
#### 问题2.我们要进一步考虑到，小王的VIP账号会不会因为频繁的解析高速连接被百度限速？
  
根据我的经验分析，百度的VIP会员是根据流量限速的，就是你的VIP账号在最近几天连续下载xxGB的文件，就会被限速，下载速度变得很慢，要等大约1周以上，才会恢复正常。
并且也会根据解析频率封IP，就是你的VIP账号一天内解析xx次（下载xx个文件），你的当前IP就被封了，不能再下载任何文件，断网换IP才恢复正常

#### 问题3.PDown的模式是让小王先把文件下载到小王的电脑，然后小李从小王的电脑下载。

首先吧，小王的电脑需要一直开着，直到下载完这个文件。并且占用小王的宽带（下载网速）
然后吧，小王的电脑还不能关，要等小李从他的电脑下载完，期间要占用小王的宽带（上传网速）
这就引申到一个概念，国内宽带都是下载快上传慢。  
最后吧，还要涉及到一个网络联通问题。小王是家庭宽带，知道企业宽带价格是家庭宽带的好几倍吗？企业凭啥多掏钱？总之小李想要连接到小王的电脑并下载，在非常理想的情况下（小王和小李住上下楼）速度非常没逻辑，普遍上就是很慢（100-200kb/s）很不稳定  

总结一下就是  

对于小王，需要长期开着电脑不关，长期忍受自己网速很慢。免费共享自己的VIP账号  
对于小李，下载速度很慢（百度免费账号没被限速，很多文件下载的时候运气好也可以达到100-300kb/s），经常下载失败（只要小李没下完之前，小王关闭PDown，就会导致小李下载失败）

#### 问题4.换个模式，只让小王解析下载地址发给小李，让小李用高速地址下载

这样问题立马就少了很多了，看起来是可行的。但实际上也有问题。  

从百度下载时需要提供下载地址+cookie（包含用户sid，stoken之类）。所以小李需要登录自己的百度账号（获得cookie）才行。然后吧下载的流量多了小李的账号会被限速，最后又成了速度很慢了（高速链接，用户被限速，最终下载速度也会很慢）


所有的，通过解析百度下载地址下载的（包括PanDownload，baidupcs-web，Proxyee-down等等等等），最终都逃不过，开始很快（多线程并发下载），流量到达一定值被百度限速，速度变很慢。这个轮回，有的人下载的文件少，下载记录i过几天被百度清0了，所以很少触发限速而已。有的人下载量很大，几天就被限速了  

所有的，都逃不过（开始快--下载流量太多--被百度限速--非常慢）  

PDown现在就是扮演小王的角色（我一直开着服务器，企业宽带，并且一直支付着流量费用），并不让用户从百度下载，所以才不受这一条影响

  
  
有想法了不？一定要继续回复我啊

**Comment by yz23095913** [comment]
看到你今天关了,不知道什么情况.
我还是把我的想法说一下,我分成三类人.

1.有会员, 也不是一个月内天天下,本地硬盘估计都不够.以后想下的时候,会员又到期了.
2.有一部分人电脑是天天开着,带宽也不可能一直用着.
3.有一部分人没会员,没带宽.

我的思路是
1.把会员在空闲的时候共享出来,攒积分.等他没会员的.可以用积分下载
2在他空闲的时候把1cookie临时拿过来,帮3下载,也可以攒积分
3帮忙刷刷流量,点点广告,然后你可以去买会员当1

说的有点乱,大概就这个思路

**Comment by yz23095913** [comment]
有兴趣或者方便就加个wei, 聊起来方便点

**Comment by pdown2020** [comment]
我明白你的意思，但是我还是感觉这个思路操作起来不现实


### 1 你还是选择走角色2下载后传给角色3的思路

这个思路从技术上，你实现不了。角色3的下载速度长期只有100-200kb/s 甚至更低。没有使用的意义。尤其是下载大文件，需要持续3-5个小时，角色2在3-5小时期间一断网/关闭软件 角色3就下载失败。

你自己想想，你现在是角色3，你想下个大文件。速度慢不说还老是失败，你会继续用吗？
更别说还要你做很多的贡献才能大量下载
（比如点100天广告兑换10GB下载流量？百度CPS广告是万次150元，你点100天可以换来1.5元）
（比如挂机10小时兑换10GB下载流量？你晚上挂一晚，也不一定刚好有人链接你从你电脑下载。就算是从你电脑下载了，你一小时也只能上传500MB-1GB的流量）


### 2 以后主流的是共享VIP，一个月6块，直接给你百度VIP账号，随便下，没任何限制

以前还有pandownoad(或者其他的)，现在大部分都停止维护了，所以大部分人还是会去共享

就算思路从技术上勉强实现了，没有很多人在用，最后还是没啥用啊

**Comment by pdown2020** [comment]
所以我并不担心PDown会做大，不可能的。没有满足免费+超高速+不限制流量  这个基本要求。不会有很多人用的，大部分人都是试试一看：
* 什么？下载速度《10MB/s 啊
* 什么？不能下载10GB的文件？
* 什么？不能下载2GB的文件？
* 什么？只能下载《100MB的文件？

呵呵，走了

**Comment by pdown2020** [comment]
我再啰嗦一句啊，你不要把你自己上传文件到网盘的体验想象成 你发送文件给别人 啊

你上传文件到网盘，因为网盘都是分配给你就近的服务器&&&服务器都是主干网络&&&服务器都是BGP多线 。所以你是满速上传的

而发送文件给别人，因为别人和你的地理位置/宽带服务商 不可控，连接质量非常差&&&非常不稳定
所以上传速度完全没规律的，可能一直是0kb/s，换个人可能一直是300kb/s

**Comment by yz23095913** [comment]
p2p的速度问题
如果角色2数量多的话,可以选速度快的.
如果是大文件,让多个角色2分段下载,然后传给3.这个可以加点速.实现难度加大了不少.
尽量保证免费的也能用.

共享VIP帐号
如果有人愿意用共享帐号.你这个完会可以把这个功能做的比闲鱼漂亮,闲鱼上的没客户端.
你整理VIP帐号,无缝分配给需要的客户端.
冲6元,随时可以用.
冲4元白天用冲2元晚上,等等.
这个你帮百度解决了收费方式单一的问题,哈哈

反正不管咋样,只要用的人多了,法律问题就来了.
要是没法律问题pandonload完会可以这样做

**Comment by yz23095913** [comment]
换个思路,你就做VIP共享的app,不提供VIP帐号.
把APP让闲鱼那帮人用,你就拿APP的流量变现,没法律问题吧

**Comment by pdown2020** [comment]
这个思路是可行的，你可以深入的研究一下。我因为只做毕业设计，并不考虑变现的问题。就不折腾了。话说今年毕业答辩什么时候答辩呢////
