### ISSUE TITLE
作者联系我，我给你提供服务器

### ISSUE THREAD

**Issue by ghboke** [pdown2020/pdown#3]
我是果核剥壳的站长(https://www.ghpym.com)，我可以给你提供大带宽的服务器，以支持这个项目进行下去，我邮箱guoheboke@gmail.com，你把你的联系发我邮箱，我加你详谈。

**Comment by pdown2020** [comment]
非常感谢你的留言，PDown是个人免费项目，就是靠大家的热情帮助才能更好。

但是现在用户量很少--我也没考虑过用户量很大的情况。
同时为了尽到版权监管责任，我已经从3月22日起调整为仅支持900MB以内的链接（电影之类体积大，自动被排除在外了）。

PDown的初衷仅仅是帮助大家临时应急，毕竟百度有自己的会员制度，所以并不会真的需求多大的宽带。

加上我个人没啥经验，遇到您的馈赠不知道怎样才处理合适，几经思虑，还是先婉拒了吧。

请不要因为我的不当而失望。您的心意我完全领受的到

**Comment by pdown2020** [comment]
今天更换线路来着，实在是忙得没顾上，回复的晚了哈
