### ISSUE TITLE
要如何部署pdown服务器呢

### ISSUE THREAD

**Issue by Ezrwal007** [pdown2020/pdown#30]
自己充了百度会员，想在宿舍部署一个大家合租

**Comment by pdown2020** [comment]
嗯，这个问题，我还真没想好。事情是这样。

现在服务器需要部署api网站(.net iis)，mssql数据库，后台模拟程序，后台监控程序，安装百度网盘客户端，部署的操作还是挺繁琐

因为PDown现在并未开源，并且我直接写死的api网址，所以还需要我调整一下PDown客户端，增加自定义网关功能。

总之是现在还没成熟，无法帮助你自行部署，以后我会参看有多少人需要自行部署，考虑调整一下放出部署的教程。现在确实没办法

**Comment by wolgy** [comment]
@pdown2020 挺有意义的一个项目。
建议开源。这样大家就不需要自己造轮子了。
比较简单的开放方式是把个人服务器相关的信息用占位符替代，然后发布出来。
这样大家可以fork了自行修改。有什么问题大家也能一起贡献代码。开源的力量比个人强~

**Comment by pdown2020** [comment]
我发了个投票，看一下有多少人有需求。人多的话我就把后台部分先开源出来

实际上你去配置后台服务器操作起来挺麻烦的。如果确实要发出来，那我得先仔细的考虑怎么重构一遍，让后台配置标准化。想想需要改动的地方真不少

先看一周后的投票结果吧

**Comment by pdown2020** [comment]
![image/自搭建调查结果.PNG](https://github.com/pdown2020/pdown/raw/master/自搭建调查结果.PNG)


320人参与（现在用户也只有400多人），结果是16需要：305不需要
所以就不折腾了，因为改动确实比较多，我最近几天懒癌又犯了，2周都没认真更新了

**Comment by OuYanghaoyue** [comment]
我觉得你可以做成类似开源图传的程序，这样也规避风险。每个部署该项目的部署者的下面有跟多的独立的使用者

**Comment by pdown2020** [comment]
> 我觉得你可以做成类似开源图传的程序，这样也规避风险。每个部署该项目的部署者的下面有跟多的独立的使用者

这个功能是不是可以做成p2p的


请参见这个issue，理论上可行，实际上并不现实

**Comment by rowankid** [comment]
需要私有化部署的都是有svip的，估计也不需要使用pdown，还是希望能开源一下，帮助更多需要的同学。

**Comment by Ezrwal007** [comment]
对的 这样可以减少服务器负载  比如说家庭，宿舍环境下  一起用一个svip  在局域网布置一个pdown  岂不美哉  这样也不会说被查水表  避免重蹈pandownload的覆辙

**Comment by Ezrwal007** [comment]
而且如果部署在宿舍的话甚至不需要客户端  直接用网页进行交互  比如很多软路由  或者刷过固件的路由器都可以用docker  openwrt系统也是linux系统 可以运行web服务 那么 只需要传入链接  密码  验证码  传出解析后的链接  调用idm等下载器下载   小白一个设想：）

**Comment by Ezrwal007** [comment]
这样就可以实现一些不能安装百度云客户端的情况下下载百度云里的东西  比如：用nas来下百度云？

**Comment by 80000v** [comment]
私有化部署有个好处就是，假如我们宿舍8个人，合伙出钱买了个svip，大家一起用，又不用担心隐私问题

**Comment by DoubleShift** [comment]
有tg群嘛，我还是想要1个得。每次都是临时开会员。
