### ISSUE TITLE
解析后看不到任何文件

### ISSUE THREAD

**Issue by Flactine** [pdown2020/pdown#31]
![2020-04-22 (1)](https://user-images.githubusercontent.com/13342427/79975046-ecd81380-84cc-11ea-9b7a-80feab72fa61.png)
解析后，没有能看到任何文件，无论刷新多少次。

**Comment by pdown2020** [comment]
额。图片上显示了，现在一条连接，只支持单文件100M,总体积500M，总文件数300

**Comment by pdown2020** [comment]
只要满足其中一条，整个链接都不会显示，只会显示提示信息
