### ISSUE TITLE
没有下载提示吗

### ISSUE THREAD

**Issue by CYH1223** [pdown2020/pdown#33]
1.今天下了一个几M大的文件然后拉取时间比我下载时间还长
2.下载完成后没有提示导致我又解析又下载一遍还好本身文件不大没花多少时间

**Comment by pdown2020** [comment]
你好

### 1 拉取时间长

这是正常的，因为有时候用的人很多
这个拉取时间啊，你在8点5分提交链接，可能1分钟就开始下载了
你在8点6分提交链接，可能要拉取1小时才开始下载

因为8点5分10秒-8点5分40秒有20多人提交了任务，但是也可能在在9点1分到12点5分之间一个人都没有
完全是无规律的，也没有任何的解决办法。模式上就限制住了


### 2 下载提示

没有下载提示，因为加上下载提示（弹窗），会增加杀毒软件误报的概率，所以不敢加

但是我不明白下载提示的作用是什么，你为什么需要下载提示呢？请回复我一下。做功能调研

我的想法是，正在下载的任务，在“下载中”界面，所以你一看，找不到任务了，那就说明下载完了，打开“已下载”界面就看到了

那么下载提示的作用是什么？

**Comment by CYH1223** [comment]
之前没看见左边有下载已完成的按钮 然后当时我的情况是：我下一个文件，因为拉取很慢，就做了别的事情，等我回去看的时候已经下载好了，但是一片空白，然后我也忘记保存在哪了，导致我又重新下了一遍。然后第二次用的时候页面上我每个地方都点了点，看到了下面有一个已完成下载的按钮，这样的话，下载完到里面去找文件位置或者什么的，没有下载提示也行。



在 2020-04-30 11:09:59，"pdown2020" <notifications@github.com> 写道：

你好

1 拉取时间长

这是正常的，因为有时候用的人很多
这个拉取时间啊，你在8点5分提交链接，可能1分钟就开始下载了
你在8点6分提交链接，可能要拉取1小时才开始下载

因为8点5分10秒-8点5分40秒有20多人提交了任务，但是也可能在在9点1分到12点5分之间一个人都没有
完全是无规律的，也没有任何的解决办法。模式上就限制住了

2 下载提示

没有下载提示，因为加上下载提示（弹窗），会增加杀毒软件误报的概率，所以不敢加

但是我不明白下载提示的作用是什么，你为什么需要下载提示呢？请回复我一下。做功能调研

我的想法是，正在下载的任务，在“下载中”界面，所以你一看，找不到任务了，那就说明下载完了，打开“已下载”界面就看到了

那么下载提示的作用是什么？
