### ISSUE TITLE
这个项目是应急的，救急不救穷，我已经在52破解论坛发现，有人公开分享这个软件了

### ISSUE THREAD

**Issue by QRQF001** [pdown2020/pdown#35]
这个项目是应急的，救急不救穷，我已经在52PJ论坛发现有人公开分享这个软件了
你应该对下载再次进行限制，比如单日下载总量不超过5G，单日下载请求次数不超过10次
为了项目的长久运行下去，我觉得有必要这样做

**Comment by yxd117** [comment]
单个文件 <100M,所有文件<500M，这就限制了很多人没法用了

**Comment by pdown2020** [comment]
嗯，感谢提醒。实际上单个文件 <100M 已经很少有人在坚持用了，只几百个人的规模，安啦

**Comment by pdown2020** [comment]
我在改版，下个版本会放开更多的限制，敬请期待

**Comment by sky-wdl** [comment]
我就是在52看到的

**Comment by dan3577** [comment]
手机登陆不了

**Comment by xsy2004** [comment]
这个被分享到IT之家公众号了

**Comment by pdown2020** [comment]
我去，服务器被挤爆了

**Comment by pdown2020** [comment]
> 这个项目是应急的，救急不救穷，我已经在52PJ论坛发现有人公开分享这个软件了
> 你应该对下载再次进行限制，比如单日下载总量不超过5G，单日下载请求次数不超过10次
> 为了项目的长久运行下去，我觉得有必要这样做

比我有预见性，我一直以为这么低的限制大家试试就都抛弃了，有人虚假宣传了吗？

**Comment by iSteveyang** [comment]
建议适当提高获取门槛

**Comment by QRQF001** [comment]
软件被发布在了这些网站上面
吾爱破解：https://www.52pojie.cn/thread-1180646-1-1.html
微信公众号：在首页搜索就可以找到
IT之家（19小时前）
我有一方小院（30天前）
优质教程小站（1小时前）
中中的杂货铺（1小时前）
希望星选（1个月前）等等等等，实在太多了
B站：BV1NQ4y1T7VS
         BV1ME411c7Uc
其他地方暂时没找
