### ISSUE TITLE
大佬牛逼，能不能把500M提升到1G啊，500M有点太小化了。

### ISSUE THREAD

**Issue by qq1056123185** [pdown2020/pdown#36]
大佬牛逼，能不能把500M提升到1G啊，500M有点太小化了。

**Comment by pdown2020** [comment]
现在不能，因为我没钱。以后可以，因为我在搞新版本。开发完工日期不知道

**Comment by muququmu** [comment]
那个那个有svip版吗？或者说有考虑这个东西吗？有的话带我一个QWQ

**Comment by sky-wdl** [comment]
我觉得不要搞pd的翻版比较好，容易翻车被抓
