### ISSUE TITLE
你好，能否联系下邮箱呢，有有些问题需咨询

### ISSUE THREAD

**Issue by iodgohub** [pdown2020/pdown#39]

**Comment by pdown2020** [comment]
直接留言即可

**Comment by iodgohub** [comment]
想看看短信这块你的需求大概什么样子

**Comment by pdown2020** [comment]
哦，原来是使用手机登录需要验证码短信，后来发现大多数人都用接码平台的免费手机号收短信，我就把登录功能关了。以后也没计划重新开通短信功能。所以现在是暂时不需要了。感谢关注

**Comment by prada216** [comment]
老大怎么登陆啊，或者有没有电报群  邮箱4477474@qq.com
