### ISSUE TITLE
请问大神网盘提取码是多少

### ISSUE THREAD

**Issue by ozgh** [pdown2020/pdown#4]
没码也下不了

**Comment by xiaosongmao123** [comment]
因为这两天我一直在改BUG，做优化之类，经常停服（导致不能用），所以我先把蓝奏的链接关了，github上开发者多，大家遇到不能用也可以理解是我在调BUG。

**Comment by pdown2020** [comment]
因为这两天我一直在改BUG，做优化之类，经常停服（导致不能用），所以我先把蓝奏的链接关了，github上开发者多，大家遇到不能用也可以理解是我在调BUG。

**Comment by ozgh** [comment]
哦，能理解，大神加油，期待不久的发布，愿意参与测试。
