### ISSUE TITLE
建议将项目开源，以便自行搭建

### ISSUE THREAD

**Issue by wlt233** [pdown2020/pdown#40]
看了一下不知道我的理解对不对，这个项目现在就是分享了您的vip账户以供大家下载。如您所说一旦使用人数过多就会导致资源耗尽。

所以是希望能把这个项目开源，允许其他人使用自己的vip账户自建平台。意义就是将传统的一个账号一拨人分享的模式，套了一个方便的平台。从而每个人下载时无需翻出公用账号再登录，而是直接往自建平台发出请求再下载。这样同时也便于公用账号的管理。

**Comment by pdown2020** [comment]
我报一下基础费用，你就明白了

1 一台网站服务器  200/月
2 一台下载服务器  370/月
3 cdn加速流量     400/月
4 oss存储+cdn回源流量 600/月

这是我现在每个月的支出，用户量在400人/月，总费用在1600元/月 
如果是用来买回源，可以买64个原价百度超级会员，或者是100+个自动续费会员

你确定你需要自己搭建？？？

**Comment by pdown2020** [comment]
你的理解还是片面的，没有注意到流量费用是多么贵

**Comment by wlt233** [comment]
但是如果照您这么计算的话 1600r/400人/月 也就是 4r/人/月。这个价格还是比原价便宜吧？何况如果没有400人这种规模，仅仅是10人以内甚至更少，完全不需要这么贵的服务器以及cdn加速吧？挂台vps上差不多了吧？

**Comment by pdown2020** [comment]
源码已上传---部分开源

**Comment by xsy2004** [comment]
这成本的太高了吧我丢，用的还是国内的服务器吗？不备案也可以用嘛？

**Comment by pongfcnkl** [comment]
可以上传到第三方网盘（比如奶牛快传https://github.com/Mikubill/cowtransfer-uploader），让第三方网盘分流的话服务器上传流量就只需要一次了

**Comment by firecckk** [comment]
不考虑使用国外服务器吗？阿里巨坑，我在用digital ocean的服务器。15刀每月租个vps就能免费3TB流量不限带宽（多个vps流量还能叠加），北美下载速度超过20MB/s。海外党求服务器源码。
