### ISSUE TITLE
加个P2P让大伙共同承担流量费用

### ISSUE THREAD

**Issue by hxl-dy** [pdown2020/pdown#43]

**Comment by pdown2020** [comment]
您并不是第一个提到P2P的了，所以借此统一的回复一下，这个issue就不close了


1 什么是p2p?
首先你从我电脑下载 心路.mp4 ，之后 第三个人想要下载 心路.mp4 的时候可以从我的电脑+你的电脑 下载。速度快了，必须是心路.mp4

2 p2p的限制

限制一  用户规模必须足够大
因为用户少了，你下载心路.mp4 第三个人想要下载 妈妈咪呀.mp4 这就没p2p的事了，只有用户规模足够大，才可能出现第二个人需要下载 心路.mp4,才能用到你p2p

限制二  文件必须统一（数量少）
同上，对于正版视频网站 来说，他只有1000部电影，有1万个用户，这一万人只能下载这1000个文件，重复率就很高了，才需要p2p


限制三  用户粘度高
你缓存了，你没打开PDown，那还是没有p2p,第三人只能从我的电脑下载--你不在线找不到你

限制四  用户反感
只要你说了有p2p功能，别管用不用得到，很多人就先卸载了


3 总结

上面一说，想来你就明白了，用户太少，文件太分散，粘度太低（下完就关了）。p2p没有意义的

**Comment by pongfcnkl** [comment]
p2p还不如上传到第三方网盘更能节省流量费用

**Comment by zwc456baby** [comment]
可以将服务器代码打包成一个 docker 镜像，在其中运行服务。让其他人可以运行该服务器（大致意思是做成分布式），这样可以让别人贡献闲置的云服务器和带宽，为客户端提供下载

之前是 客户端提交下载请求->服务器->返回内容

**Comment by zwc456baby** [comment]
当然只是一个思路，如果没人贡献闲置服务器，其实没啥用。

**Comment by LuckyCurve** [comment]
赞同发布docker镜像做成分布式这个想法，阿里云一个月学生价才十块，差不多干放着了，带宽都浪费了。

**Comment by yangweijie** [comment]
我有闲置服务器 自己买的放个博客的，3年300块

**Comment by yangweijie** [comment]
自己家用主机百兆带宽， 部署了内网穿透 zerotier 平时不关机，也可以做中转服务器

**Comment by yanyudalao** [comment]
看了一下说明，这个费用的问题不解决，这个项目是不能长久的。
非常赞同用docker的方式，毕竟有很多人是家里装了NAS和做了公网IP的，可以提供部分闲置宽带来做公益~
