### ISSUE TITLE
按照网盘文件夹格式保存

### ISSUE THREAD

**Issue by lushenghen** [pdown2020/pdown#44]
可以按照网盘文件夹格式保存吗，就是在下载的同时在本地按照网盘文件夹分类，不然下载下来一堆东西，需要自己建文件夹分类，有点难受

**Comment by pdown2020** [comment]
你好

这个分类是什么意思？

1 我设计的是，按照网盘的文件夹路径保存文件的---是程序的BUG吗？
比如你提交了一个分享链接，里面有  小学1-6年级(这是文件夹)/1年级(这是文件夹)/语文.pdf
你选择的下载目录为D:\Download\

如果你最终得到D:\Download\小学1-6年级\1年级\语文.pdf
这样是正确的，程序没有出现BUG

如果你最终得到D:\Download\语文.pdf
这样说明程序有BUG


请问是你遇到程序的BUG了吗？


2 假如不是遇到BUG，那你的意思是什么？

**Comment by lushenghen** [comment]
我得到的是D:\Download\语文.pdf，那应该是遇到BUG了吧

**Comment by pdown2020** [comment]
方便的话是否可以把链接（和提取码）告诉我，我去测试一下

**Comment by pdown2020** [comment]
嗯，我测试了，是BUG，我去修改

**Comment by lushenghen** [comment]
好的

**Comment by pdown2020** [comment]
https://www.lanzoux.com/id0bqfa


试试，应该没问题了

**Comment by lushenghen** [comment]
问题解决了，感谢！
