### ISSUE TITLE
200M感觉还是有点太小了

### ISSUE THREAD

**Issue by maduoduo52** [pdown2020/pdown#45]
大佬，可以考虑再大点吗

**Comment by pdown2020** [comment]
我没钱了。。。。

**Comment by pdown2020** [comment]
v1版采用阿里云cdn，流量费用是约0.5元/GB（cdn+oss）。你每下载1GB的文件，我要支付给阿里云0.5元。100人*每人每天下载1GB=3000GB/月=1500元/月，我花的我自己的钱

v2版开始采用廉价线路,结果是下载速度不太稳定，有的人下载速度会很快，有的人是完全不能下载。不同时间速度截然不同，请多一点耐心

**Comment by pdown2020** [comment]
廉价线路是相对阿里云廉价，每个月也是要很多钱的

**Comment by Luotas** [comment]
捐款

**Comment by hyfree** [comment]
阿里云的流量费用好像是

流量阶梯(计费单位：元/GB) | 中国内地-CN | 北美-NA | 欧洲-EU | 亚太1区-AP1 | 亚太2区-AP2 | 亚太3区-AP3 | 中东、非洲-MEAA | 南美-SA
-- | -- | -- | -- | -- | -- | -- | -- | --
0GB-10TB(含） | 0.24 | 0.46 | 0.46 | 0.58 | 0.78 | 0.69 | 1.31 | 1.31
10TB-50TB(含） | 0.23 | 0.46 | 0.46 | 0.58 | 0.78 | 0.69 | 1.31 | 1.31
50TB-100TB(含） | 0.21 | 0.39 | 0.39 | 0.45 | 0.67 | 0.60 | 1.18 | 1.18
100TB-1PB(含） | 0.18 | 0.2 | 0.2 | 0.38 | 0.57 | 0.51 | 0.98 | 0.92
大于1PB | 0.15 | 0.16 | 0.16 | 0.35 | 0.52 | 0.46 | 0.92 | 0.85
