### ISSUE TITLE
大佬需要赞助吗

### ISSUE THREAD

**Issue by insoxin** [pdown2020/pdown#48]
我们给大佬赞助个cdn费用

**Comment by pdown2020** [comment]
谢谢，我已经开始切换相对廉价的线路了，在努力坚持吧。赞助先不需要了，感谢理解也感谢帮助

**Comment by insoxin** [comment]
> 谢谢，我已经开始切换相对廉价的线路了，在努力坚持吧。赞助先不需要了，感谢理解也感谢帮助

大佬一个重要的事,我刚发现搜索功能,pand就是因为分享被干死的,新闻中也提到了，逮捕作者是因为“泄露隐私”，建议取消搜索功能啊啊啊
