### ISSUE TITLE
v2.27.05 在Windows 10中的Windows Defender报病毒

### ISSUE THREAD

**Issue by EnterpriseSolution** [pdown2020/pdown#49]
有两个地方，chrome下载完成后，在文件夹中浏览到此文件时，都报病毒。
我之前写的代码也出现过这种情况，我的代码是因为操作了WIN32 API，创建桌面快截方式
期待您能查看一下代码，看是哪里的原因导致了Windows Defender报病毒。这里不一定是病毒，可能是因为违规操作了Windows的一些权限数据。

**Comment by pdown2020** [comment]
嗯嗯呢，收到，访问winapi是违规操作？？？其实每个版本都会报毒，应该是名字（PDown）已经被加入黑名单了。只要发布就是报毒，没办法。就算改了名字，不久又会报毒的。最重的解决办法就是找个证书签名，挺贵的，没舍得弄

**Comment by pdown2020** [comment]
我在项目里有个报毒的研究文件，我理解的是，我软件是下载软件，用户用我的软件下载了病毒文件（并不是故意的，他也不知道）并且在PDown里直接打开，那我就会被怀疑是下载者木马，次数多了就肯定会报毒的。跟代码没关系。除非我改逻辑--不能下载文件--不能打开文件----这也不现实

**Comment by EnterpriseSolution** [comment]
感谢答复，原来是这个原因，能在这里开源一部分代码并告知原理的，您的软件肯定不是病毒。Windows Defender也是挺奇怪的一种存在，开启动了这个杀毒软件，电脑上所有的Office Windows激动(activator,keygen, 活)都被删了，全部都被杀
