### ISSUE TITLE
资源缓存时间

### ISSUE THREAD

**Issue by linmii** [pdown2020/pdown#50]
刚刚输入了一个地址，显示创建时间为2020-05-15 09:42:54，保存的还是之前的文件，后面追加了文件到分享地址，没有显示出来，能否提供刷新服务器缓存资源的按钮？

另外，判断文件大小能否在选择资源的下载的时候才判定是否能下载？目前限制200M，可能一个文件夹里面有多个文件超过500M/800M，但是实际只需要下载其中一个文件，没有超过200M的限制，目前也是无法下载。

感谢大佬提供这么好的工具！

**Comment by pdown2020** [comment]
第一个问题，请使用v1.1.4.4版本打开，提交链接，在选择文件的上面有强制刷新按钮。v2 改成显示链接信息了，以后会再加上强制刷新按钮


第二个问题，v2 就是根据文件去限定的，你提交链接会显示所有文件，针对200MB会改名为不支持200xxx，其他文件、目录正常显示

**Comment by pdown2020** [comment]
注意一下，v1 和v2 是完全独立的，不能v1刷新后用v2去下载，你现在先直接创建一个新的分享链接吧，以后v2更新时会加上按钮

**Comment by linmii** [comment]
> 注意一下，v1 和v2 是完全独立的，不能v1刷新后用v2去下载，你现在先直接创建一个新的分享链接吧，以后v2更新时会加上按钮

好吧，刚用V1刷新完，准备用V2下载，主要是这个是别人分享的，我没法操作
