### ISSUE TITLE
解析具有不同链接格式的pan.baidu.com链接时出错。

### ISSUE THREAD

**Issue by Evid74** [pdown2020/pdown#51]
你好

我想对这个项目表示感谢。 我发现这个应用程式非常适合我从pan.baidu.com下载档案！

我想提出一个有关链接解析的问题。 我正在尝试从具有 https://pan.baidu.com/share/link?shareid=xxxxxx&uk=xxxxxxxxxx#list 格式的链接下载文件。 但是，该程序不会让我下载具有 /share/ link?shareid 的链接？ 它以无效链接格式和解析错误返回。 您能否调查这个问题？ 如果PDown可以识别这些链接？
![image](https://user-images.githubusercontent.com/66236638/83386310-f2ffcf00-a43e-11ea-9a70-17fff33a5184.png)

谢谢！

**Comment by pdown2020** [comment]
首先从逻辑上：

百度网盘，创建分享链接，只会创建出 pan.baidu.com/s/1xxxxxxxxxxxxxxxxx  提取码：xxxx  这样的链接

您提到的/share/link?shareid=xxxx&uk=xxxx 现在已经不常见了，他是多次跳转后的链接，请直接提交原始链接即可


然后从程序上：

我的数据库是基于1xxxxxxxxxxxxxxxxx为主键去设计的，而当你提交/share/link?shareid=xxxx&uk=xxxx 这样的链接时，我无法解析出它的原始链接1xxxxxxxxxxxxxxxxx

（1xxxxxxxxxxxxxxxxx 可以方便的转换成shareid=xxxx&uk=xxxx 但反过来我没找到）

所以最总我也无法修正这个问题

**Comment by Evid74** [comment]
感谢你的帮助！ 我完全明白。 不幸的是，我找不到该文件的原始链接，因为这是我可以找到的唯一文件链接，出于研究目的，我需要该文件。
我想知道你是否知道任何可以将百度网络磁盘链接转换为https://pan.baidu.com/share/link?shareid=xxxxxx&uk=xxxxxxxxxx#list的不同格式的指令或计算机程序的合适链接格式 https://pan.baidu.com/s/1xxxxxxx？
谢谢！

**Comment by pdown2020** [comment]
1xxxxxxxxxxxxxxxxx 可以方便的转换成shareid=xxxx&uk=xxxx 但反过来我没找到

**Comment by pongfcnkl** [comment]
转存到自己账号上在分享

**Comment by Evid74** [comment]
谢谢你们的帮助。 这种方法效果很好，谢谢！ 我感谢你的帮助。
