### ISSUE TITLE
大佬 将来有可能加上监视剪贴板的功能吗 

### ISSUE THREAD

**Issue by loyalll** [pdown2020/pdown#54]
这样省去了复制粘贴的时间 会更加方便

**Comment by pdown2020** [comment]
1 你先复制，然后点击【新建下载】按钮，此时会自动识别出并自动粘贴进去（前提是你复制的格式正确）

2 并不会一直监视剪切板（就是你一复制，就自动弹出PDown下载界面）。因为容易被报告为病毒---监视剪切板

**Comment by loyalll** [comment]
> 1 你先复制，然后点击【新建下载】按钮，此时会自动识别出并自动粘贴进去（前提是你复制的格式正确）
> 
> 2 并不会一直监视剪切板（就是你一复制，就自动弹出PDown下载界面）。因为容易被报告为病毒---监视剪切板

多谢大佬
