### ISSUE TITLE
版本升级问题

### ISSUE THREAD

**Issue by Axm11** [pdown2020/pdown#55]
先前用的是V2.27.05，下载V2.30.18后双击打开，仍然显示的是V2.27.05，exe程序是直接运行无需安装的，所以第一个，这个版本咋升级，第二个问题就是，可不可以不搞强制升级才能用
![image](https://user-images.githubusercontent.com/22165259/84012552-4ecfd800-a9aa-11ea-85f3-9b7c1c55c4e3.png)

**Comment by pdown2020** [comment]
1 你没退出v2.27.05 ，这时直接运行任何版本都是直接显示v2.27.05因为你没退出

2 我喜欢强制升级，可以简单的维护版本错误---只有一个版本，所以有错误我就知道是哪里的问题。多个版本会混乱

**Comment by Axm11** [comment]
-- 好吧，我以为点了x就是关闭了，没想到任务还在运行，ok   感谢大佬
