### ISSUE TITLE
解析首页失败

### ISSUE THREAD

**Issue by fm953526** [pdown2020/pdown#56]
v2.30.18

![擷取](https://user-images.githubusercontent.com/60768678/84015905-1e3e6d00-a9af-11ea-84b2-33369689a73b.PNG)

**Comment by pdown2020** [comment]
把链接发上来我看看

**Comment by pdown2020** [comment]
你试着直接在浏览器打开链接，应该是链接本身被404了

**Comment by fm953526** [comment]
那应该是我用Chrome的插件Vpn可以打开，可能要在pc端安装Vpn才能使用你的软件

**Comment by pdown2020** [comment]
嗯
