### ISSUE TITLE
請問可以解除200M 限制嗎 謝謝

### ISSUE THREAD

**Issue by ifye0919** [pdown2020/pdown#57]
請問可以解除200M 限制嗎 謝謝

**Comment by pdown2020** [comment]
现在不能

**Comment by yangweijie** [comment]
自己有个腾讯云服务器能不能开放出个人部署只给自己加速使用 没有流量限制

**Comment by dongshige** [comment]
> 
> 
> 现在不能

能不能考虑降低总量限制，开放单个文件限制，比如每天1G总量，不限制文件（小于1G）。

偶尔需要下载几个超过200m的文件，但频率较小，再折腾其他渠道有些麻烦

**Comment by pdown2020** [comment]
你好，不可以，目的是为了限制用户数量，PDown只适合小文件，这样就把60%的人拒之门外了，我的负担就小了
