### ISSUE TITLE
我有公网企业光纤宽带。我怎么设置能用于我的朋友圈子里下载！就是不走你这边？

### ISSUE THREAD

**Issue by QingSiHuang** [pdown2020/pdown#58]
我有公网企业光纤宽带。我怎么设置能用于我的朋友圈子里下载！就是不走你这边？

**Comment by pdown2020** [comment]
很抱歉啊，因为服务器端并未开源，所以现在没有办法自行搭建的。

还是花6块买个共享号一起用吧。或者花30自己开会员，朋友一起用

**Comment by QingSiHuang** [comment]
好吧，感谢回复告知。自己个人账号内都是自己的东西~不方便共享给朋友直接登录使用，哎~~~

**Comment by QingSiHuang** [comment]
说句实话，百度网盘自己网盘客户端都不能满速下载！！！是真艹蛋

**Comment by pdown2020** [comment]
嗯，分情况吧，大部分时候官方端还是挺好的，，，，，表现差别确实挺大
