### ISSUE TITLE
如何从搜索结果中复制连接信息？

### ISSUE THREAD

**Issue by dongshige** [pdown2020/pdown#59]
部分内容想直接转存网盘

**Comment by pdown2020** [comment]
因为某些事件的警示，对可能会涉及到用户隐（fenge）私的信息，全部加密了，所以无法提取出链接信息

**Comment by dongshige** [comment]
> 
> 
> 因为某些事件的警示，对可能会涉及到用户隐（fenge）私的信息，全部加密了，所以无法提取出链接信息

理解，希望这样能规避掉风险
