### ISSUE TITLE
有没有mac版的，命令行的也行啊

### ISSUE THREAD

**Issue by wqwangwei** [pdown2020/pdown#6]
有没有mac版的，命令行的也行啊

**Comment by pdown2020** [comment]
这个还真没有，据说，仅仅是据说啊，mac用c++之类开发的软件直接发布安装包是不行的（几十人测试还行），需要申请苹果的签名证书。  
  
没接触过mac，所以没开发。另外就是界面库用的SOUI，本身也不支持mac。需要换界面库就等于重新开发客户端，工作量有点大啊。  
  
呃，是不是暴露了我穷的连mac都没摸过这件事？

**Comment by mrmign** [comment]
> 这个还真没有，据说，仅仅是据说啊，mac用c++之类开发的软件直接发布安装包是不行的（几十人测试还行），需要申请苹果的签名证书。
> 
> 没接触过mac，所以没开发。另外就是界面库用的SOUI，本身也不支持mac。需要换界面库就等于重新开发客户端，工作量有点大啊。
> 
> 呃，是不是暴露了我穷的连mac都没摸过这件事？

我有证书一直闲着，我可以给你签

**Comment by braydenwong** [comment]
mac的话考虑通过命令行的形式，比如有个python脚本，我们在mac运行，脚本里实际调用的是你服务器的内容，我们在命令行进行下载，然后返回一个文件给我们。

**Comment by braydenwong** [comment]
> > 这个还真没有，据说，仅仅是据说啊，mac用c++之类开发的软件直接发布安装包是不行的（几十人测试还行），需要申请苹果的签名证书。
> > 没接触过mac，所以没开发。另外就是界面库用的SOUI，本身也不支持mac。需要换界面库就等于重新开发客户端，工作量有点大啊。
> > 呃，是不是暴露了我穷的连mac都没摸过这件事？
> 
> 我有证书一直闲着，我可以给你签

给你点赞

**Comment by pdown2020** [comment]
> > 这个还真没有，据说，仅仅是据说啊，mac用c++之类开发的软件直接发布安装包是不行的（几十人测试还行），需要申请苹果的签名证书。
> > 没接触过mac，所以没开发。另外就是界面库用的SOUI，本身也不支持mac。需要换界面库就等于重新开发客户端，工作量有点大啊。
> > 呃，是不是暴露了我穷的连mac都没摸过这件事？
> 
> 我有证书一直闲着，我可以给你签

我竟然没留意到。。。。。抱歉

你帮我也不行啊，界面库soui只支持win，其他的都不支持（最开始是看中的他体积小，并且打包后是单文件。结果现在才知道体积不能太小）

想要跨平台，我得切换其他界面库，这就是个大工程了，但是实际上并没有啥特别优雅的跨平台方案

electron体积太大
qt文件太多（一堆dll）

**Comment by pdown2020** [comment]
> mac的话考虑通过命令行的形式，比如有个python脚本，我们在mac运行，脚本里实际调用的是你服务器的内容，我们在命令行进行下载，然后返回一个文件给我们。

我最开始并没有考虑过命令行的形式，对普通用户太不友好了。另外毕业答辩的时候截一堆命令行图片，老师会ban我的
