### ISSUE TITLE
关于支持百度云旧版分享链接的解析问题

### ISSUE THREAD

**Issue by zcazca** [pdown2020/pdown#60]
软件作者你好。如下是旧版百度云的分析链接，请问作者大大能添加如下形式的分享链接解析吗？谢谢大佬了！
链接形式：https://pan.baidu.com/share/link?shareid=*********&uk=*********
如：https://pan.baidu.com/share/link?shareid=570477101&uk=939937960

**Comment by pdown2020** [comment]
你好，我开始制作的时候经验太少，我不知道百度有这种连接，因为我创建分享链接得到的就是 链接：pan.bd.com/s/1xxxxx 提取码：xxx这种。因此我是用1xxxxx做数据库主键的。你提到的pan.baidu.com/share/link?shareid=*********&uk=*********是多次跳转后的链接

现在的问题是，我知道shareid+uk,我解析不出1xxxx 反过来我知道1xxxxx可以解析出shareid+uk

得不到1xxxxx我就无法支持后面的操作。


所以我无法支持com/share/link?shareid=这种连接

**Comment by zcazca** [comment]
好的，谢谢作者大大！
