### ISSUE TITLE
对软件版本更新的一个建议

### ISSUE THREAD

**Issue by zcazca** [pdown2020/pdown#62]
你好！首先感谢您开发的 网盘下载器， 您的软件对于自己而言真的挺好用，很好的解决了自己从百度云上下载文件资料的需求，软件使用上及其方便简洁。

但对于软件版本更新上有一个建议。建议您发布新版本的软件时，可以保持 **下载器程序** 的文件名不动，通过 **压缩文件名** 及 **其他方式** 注释版本号。这样当用户在 **创建快捷方式** 的情况下使用软件时，可以直接覆盖升级，而无需修改快捷方式指向的文件名。

例如：发布新版本时的程序压缩文档为` PDown vx.xx.zip `，压缩文件内可通过添加 **文本文件** 注释版本号并说明版本更新内容。压缩文档结构如下：
```
PDown vx.xx.zip
|
-- PDown.exe
|
-- vx.xx 版本更新内容.txt
```

压缩文件预览如下：
![image](https://user-images.githubusercontent.com/31820933/84496166-11878500-acdf-11ea-98c0-90ddbba88c2d.png)

同时，`vx.xx 版本更新内容.txt`文本文件可参考以下模板进行更新说明。
```
【版本号】
V x.xx.xx


【更新内容】
增加/修改/删除：
1.  ......
2.  ......

......

修复：
1. ......
2. ......

......


【使用方法】

......


【Q&A】
1.   xxxxxxx
答：
2.   xxxxxxx
答：

.......


【免责声明】

......
```

谢谢作者大大的 网盘下载器 ，希望您考虑我的建议。

**Comment by pdown2020** [comment]
不错哦，这个建议很中肯，会参考的
