### ISSUE TITLE
什么时候百度客服这么不专业了？？

### ISSUE THREAD

**Issue by 121181086** [pdown2020/pdown#65]
兄弟  那个是恶作剧吧  难道发件人是李某？？？  这也太不专业了  警告律师函也不是这样发的啊

**Comment by byyxx128** [comment]
悄悄地用吧，你懂的……

**Comment by byyxx128** [comment]
悄悄地用吧，你懂的……
虽然我也一看就是假的……（连个标点符号都没有……）
对了大兄弟，你也没有标点是不……你看我就能正确使用标点。

**Comment by byyxx128** [comment]
悄悄地用吧，你懂的……
虽然我也一看就是假的……（格式极其混乱，连个标点符号都没有，这是小学还没毕业的写的吧）

**Comment by byyxx128** [comment]
悄悄地用吧，你懂的……
　　虽然我也一看就是假的……格式极其混乱，连个标点符号都没有，这是小学还没毕业的写的吧。而且用个QQ邮箱发邮件……还是个小号，山寨得也太不专业了。不过尽管如此，低调使用吧。
　　说不定作者也早看出来是假的，只是发出来让大家一乐，同时提醒大家注意。因为这种软件死得快的一个原因就是——用的人太多，而用的人多就说明知道的人多，而知道的人多的一个最主要原因就是，某些软件博主有意无意地转载，虽然我也是从软件博主那儿看来的，但是这样会导致知道的人太多，最后死翘翘。

**Comment by tspor** [comment]
百度员工用 QQ 输入法?

**Comment by autumoon** [comment]
明眼人一看就知道是假的，byyxx128说的很对，但是作者也是为了规避风险，可以理解，大家低调一点就好了，非常感谢作者的辛苦付出，夹缝中生存实在是太难了，要不将来作者自己搞个良心网盘吧（笑）。

**Comment by xzkeee** [comment]
可是小学生为什么要做这个事呢,新招的临时小学员工么hhh
