### ISSUE TITLE
PDown停止开发维护的公告

### ISSUE THREAD

**Issue by autumoon** [pdown2020/pdown#68]
PDown作者真不容易，毕竟作者不是盘神，这盘好不好用大家心里还不清楚么？总之看到这个公告的童鞋，希望能够理解公告里的意思，也不要在这里道破一些东西，感谢PDown作者的辛苦付出。

**Comment by Hcreak** [comment]
李彦宏尼玛死了 草泥马的百度

**Comment by azazazazaz520** [comment]
唉……

**Comment by Poison-China** [comment]
曹尼玛的 百度！！！！
