### ISSUE TITLE
问下原理，纯粹好奇

### ISSUE THREAD

**Issue by politefeng** [pdown2020/pdown#7]
原理是自己购买一个百度网盘账号，来实现不租网盘号就能达到下载的目的吗。

1.首先自己购买百度网盘超级会员号
2，搭设服务器，接收客服端用户发送的带链接+密码的 下载链接请求
3. 执行相关操作，下载内容，并保存到服务器上或私有云存储上。
4. 然后返回高速的下载地址给请求用户

很好奇，希望作者大大解答下。  我之前临时用网盘号就去拼多多和淘宝购买。

**Comment by pdown2020** [comment]
你理解的对

1 我自己的百度VIP账号（不能用共享的那种，不稳定）
2 百度的政策要求是不允许共享账号，我只在我自己的电脑上登录自己的账号。
3 当有人需要下载小文件时，可以告诉我链接地址，我去帮他下载。下载完，我再发给他

个人项目，完全免费，所以原理就是这么简单。只是拿来做毕业设计。仅限于少量用户测试用

**Comment by politefeng** [comment]
挺棒的想法。&nbsp; 现在拼多多好多卖共享账号的可以用这种思路&nbsp; 更方便还稳定



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "pdown2020"<notifications@github.com&gt;; 
发送时间: 2020年3月25日(星期三) 中午12:15
收件人: "pdown2020/pdown"<pdown@noreply.github.com&gt;; 
抄送: "【曹力丰】"<418020378@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [pdown2020/pdown] 问下原理，纯粹好奇 (#7)





 
你理解的对
 
1 我自己的百度VIP账号（不能用共享的那种，不稳定）
 2 百度的政策要求是不允许共享账号，我只在我自己的电脑上登录自己的账号。
 3 当有人需要下载小文件时，可以告诉我链接地址，我去帮他下载。下载完，我再发给他
 
个人项目，完全免费，所以原理就是这么简单。只是拿来做毕业设计。仅限于少量用户测试用

**Comment by woytu** [comment]
> 你理解的对
> 
> 1 我自己的百度VIP账号（不能用共享的那种，不稳定）
> 2 百度的政策要求是不允许共享账号，我只在我自己的电脑上登录自己的账号。
> 3 当有人需要下载小文件时，可以告诉我链接地址，我去帮他下载。下载完，我再发给他
> 
> 个人项目，完全免费，所以原理就是这么简单。只是拿来做毕业设计。仅限于少量用户测试用

建议下载到GoogleDrive或OneDrive上

**Comment by pdown2020** [comment]
你们这些个骚操作啊。。。。厉害了
我研究研究。。。就是这两天好忙啊
