### ISSUE TITLE
台灣能使用嗎?

### ISSUE THREAD

**Issue by x8658732** [pdown2020/pdown#9]
我複製貼上的連結、提取碼格式都對
但一直顯示找不到文件
是跟百度擋台灣IP有關嗎?
感謝

**Comment by pdown2020** [comment]
台湾能否使用的问题，我还真没测试过

当你提交链接+提取码，

1 假如这个链接之前被别人提交过，
是读我们数据库里的缓存，直接显示文件列表。然后你可以正常的下载

2 假如是第一次被提交的链接，
PDown客户端自动打开链接的网页，去分析链接内文件列表
注意是在你的电脑上，PDown自动的，完全模拟你正常的操作，使用浏览器打开链接显示文件列表
（是用curl模拟，实际上并不是真的调用你的浏览器）

所以，你直接用浏览器可以打开看到文件列表，那PDown应该就可以读取出文件列表来（除非百度针对台湾提供定制化的网盘页面，和大陆的格式不一致，可能导致解析失败）
总之只要PDown最后显示出文件列表来，你就可以正常的使用


你可以回复一条分享链接+提取码，我看看，我这边可以正常读取吗。
有的分享链接很快就会失效，也可能是你试的这一条链接不对。多换几条链接试试

**Comment by pdown2020** [comment]
嗯，我今天看用户的上报日志，发现，百度确实会对部分用户屏蔽

具体表现为，同一个有效的分享链接。不同的人打开，显示的结果不一样。

**正常的**会显示文件列表或输入提取码页面
**被屏蔽**的人会显示：404 你访问的页面找不到了

具体的百度的屏蔽策略我也不知道，比如是对特定地区的IP屏蔽，还是对频繁访问的IP屏蔽，还是对被限速的账号屏蔽？我也不知道的

但是，确实有很多用户，因为百度的屏蔽，无法正常的提交分享链接。PDown也就不能继续拉取让你下载了

不知道你是不是遇到了屏蔽

**Comment by x8658732** [comment]
好像是對地區的屏蔽
台灣ip好像是被擋住的
